CREATE TABLE IF NOT EXISTS STUDENT
(
    STUDENTID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY,
    FIRSTNAME VARCHAR(40) NOT NULL,
    LASTNAME VARCHAR(10) NOT NULL,
    DEPARTMENT VARCHAR(10) NOT NULL,
    FEES DECIMAL(10, 2),
    VERSION BIGINT,
    CONSTRAINT PK_STUDENT PRIMARY KEY (STUDENTID)
);

CREATE TABLE IF NOT EXISTS COURSE
(
    COURSEID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY,
    STUDENTID BIGINT NOT NULL,
    TITLE VARCHAR(40) NOT NULL,
    LOCATION VARCHAR(40) NOT NULL,
    VERSION BIGINT,
    CONSTRAINT PK_COURSE PRIMARY KEY (COURSEID),
    CONSTRAINT FK_COURSE_STUDENT FOREIGN KEY (STUDENTID) REFERENCES STUDENT(STUDENTID)
);

CREATE TABLE IF NOT EXISTS EMPLOYEE
(
    EMPLOYEEID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY,
    FIRSTNAME VARCHAR(40) NOT NULL,
    LASTNAME VARCHAR(10) NOT NULL,
    COMPANY VARCHAR(30) NOT NULL,
    HOURLYRATE DECIMAL(10, 2),
    VERSION BIGINT,
    CONSTRAINT PK_EMPLOYEE PRIMARY KEY (EMPLOYEEID)
);

CREATE TABLE IF NOT EXISTS QUALIFICATION
(
    QUALIFICATIONID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY,
    EMPLOYEEID BIGINT NOT NULL,
    TYPE VARCHAR(10) NOT NULL,
    TITLE VARCHAR(40) NOT NULL,
    INSTITUTION VARCHAR(30) NOT NULL,
    VERSION BIGINT,
    CONSTRAINT PK_QUALIFICATION PRIMARY KEY (QUALIFICATIONID)
);
